#!/usr/bin/env python3
from easy_chain.cli         import cli_group, cli, show_help, grey, white, Response
from easy_chain.cli_wallet  import WalletCLI
from easy_chain.cli_network import NetworkCLI
from easy_chain.wallet      import Wallet
from easy_chain.network     import Network, network_conf
from easy_chain.tokens      import Tokens
from easy_chain             import __version__


network = Network()
wallet  = Wallet(network.uuid)
tokens  = Tokens(network)


@cli_group()
@cli.option('-v', '--version', 'version', is_flag=True, default=False,
    help='Show version and exit.')
@cli.option('-i', '--info', 'info', is_flag=True, default=False,
    help='Show version and exit.')
def cli(version, info):
    """
    Simple Easy Chain CLI

    Develped by Juan S. Bokser (2020)
    """
    if version:
        print(__version__)
        return
    if info:
        print('{} {}'.format(grey('Deafult network: '),
            white(network.profile)))
        print('{} {}'.format(grey('Is connected:    '),
            Response('yes' if network.is_connected else 'no')))
        return
    show_help(cli)

@cli_group(cli, 'wallet')
def wallet_cli():
    """ Referred to wallet """

WalletCLI(wallet_cli, network, wallet, tokens)

@cli_group(cli, 'network')
def network_cli():
    """ Referred to network """

NetworkCLI(network_cli, network, network_conf)



if __name__ == '__main__':
    cli()
