#!/usr/bin/env python3
from easy_chain.cli         import command, command_group, grey, white, Response
from easy_chain.cli_wallet  import WalletCLI
from easy_chain.cli_network import NetworkCLI
from easy_chain             import Wallet, Network, network_conf, Tokens
from easy_chain             import version


network = Network()
wallet  = Wallet(network.uuid)
tokens  = Tokens(network)


@command_group()
def cli():
    """
    Simple Easy Chain CLI

    Develped by Juan S. Bokser (2020)
    """

@command_group(cli, 'wallet')
def wallet_cli():
    """ Referred to wallet """

WalletCLI(wallet_cli, network, wallet, tokens)

@command_group(cli, 'network')
def network_cli():
    """ Referred to network """

NetworkCLI(network_cli, network, network_conf)

@command(name='version')
def show_version():
    """ Show version and exit. """
    print(version)

@command(name='info')
def info():
    """ Show some info and exit. """
    print('{} {}'.format(grey('Deafult network: '),
        white(network.profile)))
    print('{} {}'.format(grey('Is connected:    '),
        Response('yes' if network.is_connected else 'no')))

if __name__ == '__main__':
    cli()
